# Generated by Django 4.1 on 2022-08-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='arrival_datetime',
            new_name='end_appointment',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='booking_datetime',
            new_name='entrys_time',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='departure_datetime',
            new_name='start_appointment',
        ),
        migrations.AddField(
            model_name='category',
            name='my_doctors',
            field=models.ManyToManyField(related_name='categorys', to='doctor.doctor'),
        ),
    ]
