# Generated by Django 4.1 on 2022-08-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_arrival_datetime_entry_end_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='my_doctors',
            field=models.ManyToManyField(null=True, related_name='categorys', to='doctor.doctor'),
        ),
    ]
